# Generated by Django 3.2 on 2021-05-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='historicalcategoryproduct',
            name='measure_unit',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='category_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct', verbose_name='Categoria de Producto'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='measure_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.measureunit', verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Categoria de Producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='measure_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalcategoryproduct',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunit',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, verbose_name='fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='fecha de modificacion'),
        ),
    ]
