# Generated by Django 3.2 on 2021-05-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name="Hero's name")),
                ('group', models.CharField(max_length=50, verbose_name='Primary attribute')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heros',
            },
        ),
    ]
